### ISSUE TITLE
🐛 [BUG]: vueFlow.value.hidden type error

### ISSUE THREAD

**Issue by LeeJaeG** [bcakmakoglu/vue-flow#1145] opened 2023-10-25 06:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

        const flowItem = vueFlow.value[i];
        if (flowItem.id == checkedValue || flowItem.parentNode == checkedValue) {
            if (flowItem.hidden === 'true') {
                flowItem.hidden = false;
                flowItem.data.watched = 0;
            } else {
                flowItem.hidden = 'true';
                flowItem.data.watched += 1;
            }
        }
        
        i need change hidden value, but when i declare true and false , type is different 

### Expected Behavior

        const flowItem = vueFlow.value[i];
        if (flowItem.id == checkedValue || flowItem.parentNode == checkedValue) {
            if (flowItem.hidden === true ) {
                flowItem.hidden = 'false';
                flowItem.data.watched = 0;
            } else {
                flowItem.hidden = true;
                flowItem.data.watched += 1;
            }
        }
        
        if i change above code, error!

**Comment by bcakmakoglu** [comment] 2023-10-25 10:31
Not sure what the bug here is supposed to be besides you trying to check a Boolean against a string?

Can you elaborate a bit more on the problem here?

**Comment by bcakmakoglu** [comment] 2023-10-25 10:31
Also you can’t set “hidden” to a string either 🤔

**Comment by LeeJaeG** [comment] 2023-10-26 05:49
I know
but 
const clickGroupCategories1 = (checkedValue, previousValue) => {
    if (checkedValue == previousValue) {
        return
    }
    console.log("checkedValue : ", checkedValue)
    console.log("previousValue : ", previousValue)


    for (let i = 0; i < vueFlow.value.length; i++) {
        const flowItem = vueFlow.value[i];
        if (flowItem.id == checkedValue || flowItem.parentNode == checkedValue) {
            if (flowItem.hidden === true) {
                flowItem.hidden = false;
                flowItem.data.watched = 0;
            } else {
                flowItem.hidden = 'true';
                flowItem.data.watched += 1;
            }
        }
    }

}
 
 <Checkbox :inputId="category.key" name="category" :value="category.key" v-if="category.key !== 'A'" 
                            v-model="groupCategoryCheckbox" :disabled="category.key === 'R'"
                            @click="clickGroupCategories1(category.key)" />
                            
if i run this code, only  hidden node
but if i click checkbox, don't visivle node

**Comment by bcakmakoglu** [comment] 2023-10-26 12:04
Can you provide a reproduction for that?
[A template can be found here.](https://codesandbox.io/p/sandbox/vue-flow-basic-gfgro4)

**Comment by bcakmakoglu** [comment] 2023-10-27 10:03
Also there's a pretty simple example on toggling node / edge visibility with a checkbox: https://vueflow.dev/examples/hidden.html

**Comment by bcakmakoglu** [comment] 2023-10-30 13:34
@LeeJaeG ping

**Comment by bcakmakoglu** [comment] 2023-11-02 18:56
I'm closing this issue due to a lack of information 
If this issue persists, please provide a reproduction of your problem :) Thank you!

**Closed by bcakmakoglu** 2023-11-02 18:56 UTC
Labels: bug, triage
