### ISSUE TITLE
🐛 [BUG]: source handle can be connected to source handle of a node with only a source handle

### ISSUE THREAD

**Issue by robcomoe** [bcakmakoglu/vue-flow#390] opened 2022-11-04 13:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Hey! First of all, thank you for your fantastic work, this is a great framework :)

I encountered a bug. If you have a "start" node with just one `source` handle and no `target` handle, and another node with both a `target` and a `source` handle, and you connect the first node's `source` handle with the second's node `source` handle, the connection is automatically shifted from `source`/`source` to `source`/`target`, which is correct.

Now if you connect them the other way round, from the second's node's `source` handle to the first node's `source` handle, the connection is established as `source`/`source` which should not happen.

### Expected Behavior

Either automatically change the second's node's connection handle from `source` to `target`, or reject the connection at all.

### Steps To Reproduce

1. You can reproduce this in the basic example here: https://vueflow.dev/examples/
2. Remove all the connections between the nodes
3. connect the `source` handle of Node 3 with the `source` handle of Node 1
4. the connection is established which should not be possible

### Anything else?

See the bug in action here:

https://user-images.githubusercontent.com/117455288/199980564-b8f346fd-6ccd-49b1-b3a1-77f54a9f0525.mov

**Comment by bcakmakoglu** [comment] 2022-11-04 15:18
Thanks for reporting, I'll see what is going wrong 😄

**Comment by bcakmakoglu** [comment] 2022-11-04 15:51
Alright, so there is a bug but I think there's also a misunderstanding here as well.

First - the misunderstanding.
When `ConnectionMode` is set to `Loose` (which it is by default), all connections are allowed. Meaning source/source and target/target are actually allowed.
When `ConnectionMode` is set to `Strict` these connections aren't allowed *at all* and will not produce a valid connection, so there won't be connections that are source/source which are then changed to source/target.

Second - the bug.
The behavior seen in the video is technically the behavior that React Flow has for `ConnectionMode.Loose` but in my opinion that is confusing to a user, as connections seem to jump to "unrelated" Handles (imagine a complex custom Node where Handles aren't just small dots, a user might be very confused why his edge is suddenly connecting somewhere completely different). So the right behavior for `ConnectionMode.Loose` in Vue Flow is that regardless of the Handle `type` (`source` or `target`), connections can be made.

I'd be open to discuss if the React Flow behavior should be adapted for `ConnectionMode.Loose` and the behavior that all connections are valid with all handles put into a new `ConnectionMode`, something called `All` for example.

**Comment by robcomoe** [comment] 2022-11-04 16:29
Thanks for the fast response!
I see I can reproduce this bug on React Flow as well, so maybe it would be better to make a bug report there.

> Though for the time being, I will fix the "jumping" behavior to what I intended it to be 😄
So what exactly was your intention here?

I think the "jumping" behaviour is actually a nice feature, it just holds the bug that it won't "fix" the connection in this edge case I mentioned.

Our need is that we implement a graphical programming environment similar to NodeRed, where we have to make sure that such backlinks are not allowed.

So for now, we can switch to strict mode and get around the problem, but then we loose the nice feature of auto-correcting ("jumping").

**Comment by bcakmakoglu** [comment] 2022-11-04 17:07
My intended behavior, as described, is that `Loose` allows *any* handle connections, the `type` is basically ignored. So regardless of `source` or `target` type, it will allow a connection.
The "auto-correcting" or "jumping" is the bug in regards to the intended behavior. Either all connections are allowed or only those from `source` to `target` handles (and vice versa).

If you want to have this "jumping" behavior, you can just adjust your connection params when the `onConnect` event is triggered.
You would have to use some internal properties to get there (for example, if you need to find out what handles your node actually has you can use `node.handleBounds` which contains `target` and `source` handle elements which you can reference in new connections.
A new connection requires a `source` and `target` node id, handle ids are optional. So you can force a connection to use a different handle by setting `sourceHandle` or `targetHandle` to whatever handle id you want.

**Comment by bcakmakoglu** [comment] 2022-11-04 17:26
Also, the jumping mechanism never auto-corrected anything. If you were to save these elements with the parameters given, you would have edges who would always try create lines between handles they aren't supposed to.
Vue Flow then would have to account for that and always try to find a correct connection instead (which could be different from what the actual parameters were you put in).

I'm imagining a scenario like this:

- You have two nodes with a couple handles, let's say 3 source and 3 target handles
- You make a connection from node `1` to node `2`, drawing a line from source handle to source handle
- As this is not "allowed", we need to correct it to another handle. Which one should I use? There are 3 handles to choose from. 
	- Do I just pick the first one? 
	- How do I account for Handles that possibly have the `connectable` prop set to `single`? Meaning they only allow for a single connection and not multiple
	- Do we check each Handle if it can still be connected to and if not, try the next one until we have tried all?

This seems like too many assumptions that I would have to make to actually correct the connection.

I hope this clears up my reasoning on why I want to avoid the jumping.

**Comment by bcakmakoglu** [comment] 2022-11-04 21:09
Behavior is fixed in `1.2.2` to what is currently intended (as described in the posts above).

If you'd like to propose a different connection mode, please open a Feature Request in the Discussions board :)

**Closed by bcakmakoglu** 2022-11-04 21:09 UTC
Labels: bug

**Comment by robcomoe** [comment] 2022-11-07 10:14
Thanks for your explanation, that makes it clearer now.
In our usecase, it is not allowed to make branches, that means each handle can only hold one connection. Plus, each node has either 0 (a "start" node) or 1 `target` handle. So in our case, it is always clear how to re-wire.
But I understand that this is a specific edge case that has not necessarily considered to be implemented.
So I'll stick to the `Strict` connection mode and implement the correction algorithm myself as you described.
Anyways, thanks again for the help and effort!
