### ISSUE TITLE
🐛 [BUG]: Fit view doesn't work if tab is not in focus while VueFlow is loading

### ISSUE THREAD

**Issue by alexgrozav** [bcakmakoglu/vue-flow#1636] opened 2024-10-10 12:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When you refresh the page and switch to another tab while VueFlow is loading, then come back, the view is not centered (`fitView` is not working). I suppose the window bounding box might not be correct while the tab is not focused.

### Expected Behavior

When you refresh the page and switch to another tab, and come back, the view should be centered if `fitView` is called.

### Steps To Reproduce

1. Refresh page - wait until old page is unloaded and new page starts loading
2. Switch tab while VueFlow is loading 
3. The view is not centered (`fitView` is not working)

https://github.com/user-attachments/assets/5b9f48b4-b1d3-4b8c-840d-b62c8d53c5ae

**Comment by bcakmakoglu** [comment] 2024-10-10 13:58
This isn't really a bug of VueFlow but one of the way the docs are using the repl.
Can't work around this atm so I'm closing it since it's a no-fix issue.

Might switch to remote examples with a sandbox link at some point though, which would resolve the issue.

**Comment by alexgrozav** [comment] 2024-10-23 18:19
It's not only in the docs. We're seeing this behaviour consistently in n8n, which has a bit longer async loading times. 

I'm able to reproduce it using a simple example here: https://stackblitz.com/edit/sb1-ndokqv?file=src%2FApp.vue

**Comment by bcakmakoglu** [comment] 2024-10-24 08:34
Mhhh okay, I’ll give it a look once I’m back from my vacation since I don’t have my Mac with me and can’t really check it now.
I’ll reopen the issue for now :)

**Comment by bcakmakoglu** [comment] 2024-11-01 09:47
I can't reproduce this issue locally.
Any chance you're updating the container size *after* loading is done and VueFlow is mounted?
If the container size changes by the time fit view is triggered it would only try to fit around the size of the view that it recognized during the mounting process and not afterwards, which I'm thinking is what happens (same thing happens in the docs for example ^^).

**Comment by bcakmakoglu** [comment] 2024-11-01 09:51
Also another thing I notice in the repro is that you use `vueFlowInstance.fitView()` but from what I can tell there is no variable available called `vueFlowInstance`.

Either you use sth like this:
```ts
const { fitView } = useVueFlow();

onMounted(async () => {
  await new Promise((resolve) => {
    setTimeout(() => {
      nodes.value = initialNodes;
      edges.value = initialEdges;

		
	  setTimeout(() => {
		fitView();
	  }, 0)
      resolve();
    }, 1000);
  });
});
```

or you try simply setting `<VueFlow fit-view-on-init ...>`

**Comment by bcakmakoglu** [comment] 2024-11-04 11:49
@alexgrozav ping :)

**Comment by alexgrozav** [comment] 2024-11-04 11:50
Hey! Trying the suggestion out now 🙏

**Comment by alexgrozav** [comment] 2024-11-04 11:57
Yup, the suggestion works. Wasn't able to reproduce. The workaround I came up with is this one:

```
onNodesInitialized(() => {
    fitView();
});
```

I suppose it's pretty much the same. Thanks a lot for taking the time to look into it!

**Closed** 2024-11-04 11:58 UTC
Labels: bug, triage
