### ISSUE TITLE
🐛 [BUG]: Keydown inside node affects selection box

### ISSUE THREAD

**Issue by salmasov** [bcakmakoglu/vue-flow#609] opened 2023-01-16 08:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Selection Box is present after pressing shift inside input within node

### Expected Behavior

Selection box is NOT present after pressing shift inside input within node

### Steps To Reproduce

1. Focus on input inside node
2. Press `Shift` 
3. Click on background of vueflow
4. Selection box is present

REPRO: https://codesandbox.io/s/vue-flow-selection-capture-uw5bto?file=/src/nodes/CustomNode.vue:321-334

**Comment by bcakmakoglu** [comment] 2023-01-16 08:37
I'm not sure how this is supposed to be a bug? What other behavior should happen here?

You press Shift -> Selection key code is triggered, i.e. a box can be drawn.

If you don't want it triggered you gotta change the selection key code to something else that isn't necessarily used inside an input or just disable it (using key code `null`) while you're focusing an input.

**Comment by salmasov** [comment] 2023-01-16 08:47
> I'm not sure how this is supposed to be a bug? What other behavior should happen here?
> 
> You press Shift -> Selection key code is triggered, i.e. a box can be drawn.

My suggestion is to prevent event from bubbling from node to VueFlow component

`
Press Shift on VueFlow and VueFlow only -> selection key code is triggered
Press Shift on input inside node -> selection key code is not triggered 
`

Is that possible?

**Comment by bcakmakoglu** [comment] 2023-01-16 08:59
Selection key listeners are global (i.e. listening to the window events), so no, that would not be possible and it's not a bug either, that is a design choice at this point.

There is no "bubbling" from node to vue flow as the event isn't caught on the node itself but the window (as mentioned).

Plus I don't see why this is an issue at all? Is this in any way blocking for you?

**Comment by salmasov** [comment] 2023-01-16 09:04
When you press `Shift` inside input, and let it go -> VueFlow stuck in SelectionBox state, because there is no listener for `keyup` event

https://user-images.githubusercontent.com/36544178/212639032-8ab24caf-39a7-4e28-85ca-8024bf92f685.mov

**Comment by bcakmakoglu** [comment] 2023-01-16 09:20
Ah, you should've said *that*, that looks more like an issue than what you described previously ^^
I'll see what I can do.

**Comment by salmasov** [comment] 2023-01-16 09:23
> Ah, you should've said _that_, that looks more like an issue than what you described previously ^^

I was a prisoner of my interpretation of the problem. Sorry for that :^)

I tried to write a solution instead of describing the problem

**Comment by bcakmakoglu** [comment] 2023-01-16 17:51
@salmasov 
Should be fixed with `1.12.2`, please install that version and lmk if you still experience any problems.

**Comment by bcakmakoglu** [comment] 2023-01-17 11:25
I'll assume this is resolved. If you still experience an issue, please re-open the issue :)

**Closed by bcakmakoglu** 2023-01-17 11:25 UTC
Labels: bug
