### ISSUE TITLE
🐛 [BUG]: Each addNode remounts the previous node

### ISSUE THREAD

**Issue by f2511571150** [bcakmakoglu/vue-flow#1207] opened 2023-12-05 02:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

I added a custom Input node via v-model:nodes="nodes", and console.log the onMounted Input node to see that every time I added a new node to nodes,? onMounted is executed once on the Input node；

![image](https://github.com/bcakmakoglu/vue-flow/assets/75900359/831c65c8-8d23-4046-a49d-0b14a28b856c)

### Expected Behavior

My expectation is that every time I add a new node, I don't have to remount the old one

**Comment by bcakmakoglu** [comment] 2023-12-06 06:51
Can you provide a reproduction for this issue?

You can find a template for a sandbox here: https://codesandbox.io/p/devbox/cranky-williamson-lmw8sy

**Comment by bcakmakoglu** [comment] 2023-12-09 15:45
We temporarily close this due to the lack of enough information. Please provide a minimal reproduction to reopen the issue. Thanks.

**Closed by bcakmakoglu** 2023-12-09 15:45 UTC
Labels: bug, triage

**Comment by dengbupapapa** [comment] 2024-05-08 02:25
This problem exists with elements registered with template, but not with node-types and edge-types

**Comment by bcakmakoglu** [comment] 2024-05-08 07:33
@dengbupapapa Can you explain your situation a bit more?
You're using the `addNodes` action + template slots?

**Comment by dengbupapapa** [comment] 2024-09-11 08:07
> @dengbupapapa Can you explain your situation a bit more? You're using the `addNodes` action + template slots?
This problem exists with elements registered with template，The following uses do not have the above problems.
  <vue-flow
    :node-types="nodeTypesAll"
    :edge-types="edgeTypesAll"
    v-model="elements"
  >
