### ISSUE TITLE
Total JS heap size increases as the length of total elements in the graph increases.

### ISSUE THREAD

**Issue by vvroul** [bcakmakoglu/vue-flow#28] opened 2022-02-11 09:07 UTC
Watching the heap snapshot while have created 200+ nodes and their respective edges, total heap size grows up to 1GB
and navigation (alongside any other functionality in the flow pane) is also lagging. That behavior is also noticeable in the "Empty" example of the Vue flow, while adding many nodes.

**Comment by bcakmakoglu** [comment] 2022-02-11 12:32
Just did a quick check on the v0.4.x release and doesn't seem to be an issue there anymore.
200+ nodes seem to result in a heap size of ~30mb and no lags whatsoever.

I'll be closing the issue for now as i won't be adding new updates to v0.3.x (*it will be deprecated soon*) and the problem doesn't occur in the next release.

**Comment by vvroul** [comment] 2022-02-11 13:55
Returning to this issue again, I tried installing the pre-release version with `yarn add @braks/vue-flow@next`.
Is the issue fixed with this pre-release version or I need to wait for the stable release to test for the changes? 

Just a note for testing : I'm adding 200+ nodes one by one while clicking let's say, on the pane, not in a for loop for example. 
Indeed rendering the elements in a for loop does have 20-30MBs of heap size while panning is lagging. 
But adding the elements "fast clicking" one by one results again to ~200MBs for 200 nodes.

**Comment by bcakmakoglu** [comment] 2022-02-11 13:59
I believe the next tag doesn't have the actual latest changes as I've been absent for a while.
Will check though if I can reproduce it - btw what Browser(s) were you using?

**Comment by vvroul** [comment] 2022-02-11 14:00
I'm using Google Chrome but I've noticed this issue on Firefox also.

**Comment by vvroul** [comment] 2022-02-14 12:58
Hello, do you have any updates on this issue?

**Comment by bcakmakoglu** [comment] 2022-02-14 13:54
@vvroul 
Sadly no, I can re-create *an issue* by for example using the Stress-Example, switching to another Example and switching back to the Stress-Example, which causes the heap to grow and grow with each switch, i.e. it seems that state objects aren't collected properly as the amount of Objects/Arrays seems to exactly double.
I've been looking into it, trying to clear all references to the state when the VueFlow component is unmounted but sadly did not achieve the results I was hoping for. 

Though thankfully the stack does not grow to 1GB of size even when rendering 400+ Nodes (it's at around 56MB when not switching between examples).

I will try to further investigate the issue.

**Comment by bcakmakoglu** [comment] 2022-04-21 18:05
@vvroul fyi
After long analysis and trying basically everything that came to mind I think I got it down to some specific issues, namely disposal of some watchers, state values and resize observers.
My latest test in the Empty Example seemed to work as expected: I click a button about ~200 times and during that time the stack size *does* increase (as nodes are made reactive so there's going to be some overhead) - you wait a little and the stack gets reduced by 10-15mb again so gc has kicked in and collected whatever was free to collect after setting up the new node(s).

Couple more optimizations helped reduce the initial stack further too.

I did notice, though, that if you're using vue dev-tools the stack will keep increasing (regardless of a vue flow component even existing) because it seems like the dev-tools keeps referencing old states, turning dev-tools off helps in such cases.

The optimizations will be published in 0.4.8 I believe, as there's no API breaking changes anyway but I want to test it a little more before releasing.

**Closed** 2022-04-24 11:34 UTC
Labels: enhancement, help wanted, performance
