### ISSUE TITLE
🐛 [BUG]: NodeResizer enforces minWidth and minHeight too much

### ISSUE THREAD

**Issue by delphi-sucks** [bcakmakoglu/vue-flow#1099] opened 2023-09-15 10:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

If a node is added with a NodeResizer with `minWidth` or `minHeight` set, than the Node is forced to this size.

See Issue https://github.com/bcakmakoglu/vue-flow/issues/1070 and the PR https://github.com/bcakmakoglu/vue-flow/pull/1087

The issue exists since **1.3.4** and also effects the example of NodeResize von [vueflow.dev](https://vueflow.dev/examples/nodes/node-resizer.html).

### Expected Behavior

`minWidth` and `minHeight` shouldn't set the dimensions on the initialization to the min. sizes.

### Steps To Reproduce

1. Create a Node with NodeResizer and a set `minWidth` and `minHeight` to `1`
2. Either define a size with `style="width: Xpx"` or create a node with a div Element with text (see [official example](https://vueflow.dev/examples/nodes/node-resizer.html))
=> After loading vue-flow with the node, the node gets instantly resized to `minWidth`/`minHeight`

**Note:** Not setting `minWidth`/`minHeight` enforces the default (`10`), but the node doesn't get resized.

### Anything else?

* [Official NodeResizer example](https://vueflow.dev/examples/nodes/node-resizer.html)

**Comment by bcakmakoglu** [comment] 2023-09-15 14:54
I guess the problem is, if the node's dimensions are > than the min height/width that the node is forced down to a different size instead of staying the size it is, is that right?

**Comment by delphi-sucks** [comment] 2023-09-16 05:04
That's right. It gets generally forced down to the minWidth and minHeight (if explicitly set).

**Comment by bcakmakoglu** [comment] 2023-09-16 05:52
Ok thanks for reporting :) I'll fix that

**Comment by bcakmakoglu** [comment] 2023-09-25 11:34
Will be fixed with release `1.23.0` - will be released some time this week

**Comment by bcakmakoglu** [comment] 2023-10-06 16:10
Fixed with `@vue-flow/node-resizer@1.3.5`

**Closed by bcakmakoglu** 2023-10-06 16:10 UTC
Labels: bug
