### ISSUE TITLE
🐛 [BUG]: Build system returns errors

### ISSUE THREAD

**Issue by dalduba** [bcakmakoglu/vue-flow#1102] opened 2023-09-24 14:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

Trying to run the build system of this repo

$ pnpm dev

The build system returns errors

`
@vue-flow/examples-vite:dev: Unable to resolve `@import "node_modules/@vue-flow/core/dist/style.css"` from C:/Users/roman/workspace/vue-flow/examples/vite
@vue-flow/examples-vite:dev: [postcss] ENOENT: no such file or directory, stat 'C:\Users\roman\workspace\vue-flow\examples\vite\node_modules\@vue-flow\core\dist\style.css'
@vue-flow/examples-vite:dev: 5:18:16 PM [vite] Internal server error: [postcss] ENOENT: no such file or directory, stat 'C:\Users\roman\workspace\vue-flow\examples\vite\node_modules\@vue-flow\core\dist\style.css'
@vue-flow/examples-vite:dev:   Plugin: vite:css
@vue-flow/examples-vite:dev:   File: C:/Users/roman/workspace/vue-flow/examples/vite/index.css
`

$ pnpm -v
8.7.6

$ node -v
v18.18.0

### Expected Behavior

Successful build and open test page

### Steps To Reproduce

1. Clone the repo and cd to it
2. npm i -g pnpm
3. pnpm i
4. pnpm dev

### Relevant log output

```shell
pnpm dev

> @vue-flow/monorepo@0.0.0 dev C:\Users\roman\workspace\vue-flow
> pnpm build && turbo dev --filter='./packages/*' --filter=@vue-flow/examples-vite


> @vue-flow/monorepo@0.0.0 build C:\Users\roman\workspace\vue-flow
> turbo build --filter='./packages/*' --filter=!vueflow

╭────────────────────────────────────────────────────────────────────────╮
│                                                                        │
│                   Update available v1.9.6 ≫ v1.10.14                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.10.14    │
│               Run "npx @turbo/codemod update" to update                │
│                                                                        │
│      Follow @turborepo for updates: https://twitter.com/turborepo      │
╰────────────────────────────────────────────────────────────────────────╯
• Packages in scope: 
• Running build in 0 packages
• Remote caching disabled

No tasks were executed as part of this run.

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    337ms

╭────────────────────────────────────────────────────────────────────────╮
│                                                                        │
│                   Update available v1.9.6 ≫ v1.10.14                   │
│    Changelog: https://github.com/vercel/turbo/releases/tag/v1.10.14    │
│               Run "npx @turbo/codemod update" to update                │
│                                                                        │
│      Follow @turborepo for updates: https://twitter.com/turborepo      │
╰────────────────────────────────────────────────────────────────────────╯
• Packages in scope: @vue-flow/examples-vite
• Running dev in 1 packages
• Remote caching disabled
@vue-flow/examples-vite:dev: cache bypass, force executing b115a827b644c37e
@vue-flow/examples-vite:dev: 
@vue-flow/examples-vite:dev: > @vue-flow/examples-vite@0.0.0 dev C:\Users\roman\workspace\vue-flow\examples\vite
@vue-flow/examples-vite:dev: > vite --open
@vue-flow/examples-vite:dev:
@vue-flow/examples-vite:dev: Duplicated imports "toRef", the one from "vue" has been ignored
@vue-flow/examples-vite:dev: Duplicated imports "toRef", the one from "vue" has been ignored
@vue-flow/examples-vite:dev: 
@vue-flow/examples-vite:dev:   VITE v4.3.5  ready in 2014 ms
@vue-flow/examples-vite:dev:
@vue-flow/examples-vite:dev:   ➜  Local:   http://localhost:5173/
@vue-flow/examples-vite:dev:   ➜  Network: use --host to expose
@vue-flow/examples-vite:dev: Unable to resolve `@import "node_modules/@vue-flow/core/dist/style.css"` from C:/Users/roman/workspace/vue-flow/examples/vite
@vue-flow/examples-vite:dev: [postcss] ENOENT: no such file or directory, stat 'C:\Users\roman\workspace\vue-flow\examples\vite\node_modules\@vue-flow\core\dist\style.css'
@vue-flow/examples-vite:dev: 5:18:16 PM [vite] Internal server error: [postcss] ENOENT: no such file or directory, stat 'C:\Users\roman\workspace\vue-flow\examples\vite\node_modules\@vue-flow\core\dist\style.css'
@vue-flow/examples-vite:dev:   Plugin: vite:css
@vue-flow/examples-vite:dev:   File: C:/Users/roman/workspace/vue-flow/examples/vite/index.css
@vue-flow/examples-vite:dev:
```

**Comment by bcakmakoglu** [comment] 2023-09-25 08:34
Mh... works fine for me when cloning freshly and following the instructions.
Are you sure you didn't change anything? Any issues if you run `pnpm build` first and then try to run `pnpm dev`?

**Comment by dalduba** [comment] 2023-09-25 19:08
> Mh... works fine for me when cloning freshly and following the instructions. Are you sure you didn't change anything? Any issues if you run `pnpm build` first and then try to run `pnpm dev`?

Nothing was changed by me before build.

Tried to run in Ubuntu 22.04 under WSL (Windows Subsystem for Linux) and it works.
Thus the build system is not working natively on windows for me.

**Comment by dalduba** [comment] 2023-09-25 19:15
pnpm build output:

`
pnpm build

> @vue-flow/monorepo@0.0.0 build C:\Users\roman\workspace\vue-flow
> turbo build --filter='./packages/*' --filter=!vueflow

• Packages in scope: 
• Running build in 0 packages
• Remote caching disabled

No tasks were executed as part of this run.

 Tasks:    0 successful, 0 total
Cached:    0 cached, 0 total
  Time:    678ms
`

**Comment by bcakmakoglu** [comment] 2023-09-25 20:03
Mh... okay, maybe this is a windows issue, I'll try to reproduce this on my desktop 😄

**Comment by bcakmakoglu** [comment] 2024-07-27 11:35
Tried on my windows machine and I couldn't reproduce the issue :/

Is this still a problem? If it is, please re-open the issue otherwise I'll close it for now since I can't reproduce it myself

**Closed by bcakmakoglu** 2024-07-27 11:35 UTC
Labels: bug, triage
