### ISSUE TITLE
🐛 [BUG]: <title> vue-flow is not hack with uniapp-h5-vue

### ISSUE THREAD

**Issue by vanexwh** [bcakmakoglu/vue-flow#1332] opened 2024-02-23 00:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

when I use vue-flow，there is a syntax error shows me (The requested module '/node_modules/@dcloudio/uni-h5-vue/dist/vue.runtime.esm.js' does not provide an export named 'toValue' (at @vue-flow_core.js?v=8e9793bf:4:160). It seems like the uni-h5-vue does not provide 'toValue'.

tips:
@vue-flow/core v1.1.1 - v.1.32.1
@uni-h5-vue v3.0.0-3081220230817001

### Expected Behavior

Which version does not use the hook which named 'toValue'?

**Comment by bcakmakoglu** [comment] 2024-02-23 07:08
Again, what I said last time you opened this issue.
You give me 0 info to go on (ok this time you gave me that you tried some VueFlow versions).
No reproduction, no code, I don't even know what library that is supposed to be.

In short: Not enough info to help you.
If I had to guess what the problem is: You're using a Vue version <3.3
Update your Vue version to at least 3.3 and see if that helps.

Though - I am really sorry but I will keep closing these issues until you provide me proper info to debug this.

**Closed by bcakmakoglu** 2024-02-23 07:08 UTC
Labels: bug, triage

**Comment by bcakmakoglu** [comment] 2024-02-25 12:28
Btw, maybe just join the Discord and open a discussion there, that way we can exchange some info quicker and get you a solution for the problem you're facing here 😄 
[Discord Link.](https://discord.gg/rwt6CBk4b5) @vanexwh

**Comment by vanexwh** [comment] 2024-03-12 01:58
Oh, I'm sorry about that.

This is the error details: SyntaxError: The requested module '/node_modules/.pnpm/@dcloudio+uni-h5-vue@3.0.0-3081220230817001_vue@3.4.21/node_modules/@dcloudio/uni-h5-vue/dist/vue.runtime.esm.js' does not provide an export named 'toValue' (at @vue-flow_core.js?v=cd600134:4:160)

**Comment by vanexwh** [comment] 2024-03-12 02:12
> Oh, I'm sorry about that.
> 
> This is the error details: SyntaxError: The requested module '/node_modules/.pnpm/@dcloudio+uni-h5-vue@3.0.0-3081220230817001_vue@3.4.21/node_modules/@dcloudio/uni-h5-vue/dist/vue.runtime.esm.js' does not provide an export named 'toValue' (at @vue-flow_core.js?v=cd600134:4:160)


Code snippet:
<img width="1238" alt="image" src="https://github.com/bcakmakoglu/vue-flow/assets/39259856/c0e125c2-b42c-484b-ae25-cada39737968">
<img width="1225" alt="image" src="https://github.com/bcakmakoglu/vue-flow/assets/39259856/46184cf4-34e5-4df2-ac9b-b61db0102724">

I import VF with an extra component, but the browser throw an error. No other operation.

**Comment by vanexwh** [comment] 2024-03-12 02:22
@bcakmakoglu Hey,buddy. I need u!!!
