### ISSUE TITLE
Missing arrow end/start of an Edge

### ISSUE THREAD

**Issue by mianlang** [bcakmakoglu/vue-flow#175] opened 2022-06-07 02:34 UTC
## Expected Behavior
An arrow appears on the end of the edge when `makerEnd` property given.

## Current Behavior
No arrows on edges.

## Steps to Reproduce
https://vueflow.dev/examples/edges.html
```
{
  id: 'e5-7',
  ...someProperties,
  markerEnd: MarkerType.ArrowClosed,
}
```
But there is no arrow pointing to Output 7 from Node 5 on Preview.

## Detailed Description
I noticed slight difference on type definition of `markerEnd` property when compared with React Flow. I've tried altering `markerEnd: MarkerType.Arrow` to `markerEnd: { type: MarkerType.Arrow }` as docs of React Flow suggest. Arrows still missing. I wonder if this has something to do with it.

Similar behavior on `makerStart`, too.

Or does it need some additional styling file or scripts to apply?

**Comment by bcakmakoglu** [comment] 2022-06-07 05:31
Thanks for reporting.
The issue is fixed an will be released with 0.4.18 - probably sometime today/tomorrow 😄

**Closed** 2022-06-07 16:33 UTC
Labels: bug

**Comment by bcakmakoglu** [comment] 2022-06-07 16:37
released with [`0.4.18`](#170)

**Comment by xieanwen** [comment] 2026-05-15 10:40
Arrow is not effective

**Comment by bcakmakoglu** [comment] 2026-05-15 11:47
Works perfectly fine in the examples: https://vueflow.dev/examples/edges/markers.html

You'll have to give more context than "does not work".
