### ISSUE TITLE
🐛 [BUG]: <npm install is not the latest version>

### ISSUE THREAD

**Issue by wang-ran** [bcakmakoglu/vue-flow#345] opened 2022-10-17 07:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and this is a new bug.

### Current Behavior

When using NPM installation, the 1.0.0 version is installed

### Expected Behavior

install the latest version (1.1.3)

**Comment by bcakmakoglu** [comment] 2022-10-17 07:14
No idea what you're doing to install (did you just define the version manually in your package.json?)
Because
1. 1.1.3 is the *latest* tag 
<img width="207" alt="image" src="https://user-images.githubusercontent.com/78412429/196112204-b0b7b113-57a5-4abe-bf25-f0b737b56a53.png">

2. It shows up as latest on npm
<img width="471" alt="image" src="https://user-images.githubusercontent.com/78412429/196112147-3f6456cf-54eb-4c80-8528-7e37da2e3268.png">

3. It shows up as latest when checking version via npm 
<img width="423" alt="image" src="https://user-images.githubusercontent.com/78412429/196112093-3c0ec219-c3f5-4631-8249-987f1e1e3450.png">

So I'll close this because it's not a bug and using `npm i @vue-flow/core@latest` does install the latest version.

**Closed by bcakmakoglu** 2022-10-17 07:14 UTC
Labels: bug, triage
