### ISSUE TITLE
Can't use vue-flow in popup

### ISSUE THREAD

**Issue by hrenly** [bcakmakoglu/vue-flow#164] opened 2022-06-03 11:15 UTC
# Title
I try to use vue-flow in popup (quasar dialog https://quasar.dev/vue-components/dialog), but component gets pane-ready event only after window resized

## Expected Behavior
Vue-flow gets pane-ready event when a popup was show

## Steps to Reproduce
Put vue-flow to a popup and open this popup

**Comment by bcakmakoglu** [comment] 2022-06-03 11:37
Hey, thanks for reporting.

I see the issue in a reproduction.
There seems to be something wrong with the dimension detection of the viewpane so the opacity value never changes and nodes aren't shown and if nodes aren't shown, edges aren't rendered either.
I'll look into it.

**Comment by bcakmakoglu** [comment] 2022-06-03 16:42
@hrenly 
Okay so what I *can* fix is, is that the Viewpane should display all nodes after properly mounting and detecting some dimensions from it's container. (will be released with the next version but it's not necessary for the solution below)

⚠️ **But** depending on the transition that's used that will result in edges not properly connecting - the issue is the transition applied by the q-dialog, mainly the `fade` and `rotate` transitions. Other transitions seem to work fine.
Handle positions (and thus edges) depend on `getBoundingClientRect` which returns a wrong value when the above transitions are applied.

🪴 There is a solution, though!
You can remedy the problem by showing your flow component after the q-dialog fires the `show` event and hide your component when the `before-hide` or `hide` events are triggered.

```vue | pure
<script>
import { ref } from 'vue'
import BasicFlow from './BasicFlow.vue'

export default {
  components: { BasicFlow },
  setup() {
    return {
      show: ref(false),
      isReady: ref(false),
    }
  },
}
</script>

<template>
  <div class="q-pa-md q-gutter-sm">
    <q-btn label="Open Flow" color="primary" @click="show = true" />

    <!-- Listen to the @show event and only mount component when the dialog is shown, otherwise destroy it -->
    <q-dialog v-model="show" transition-show="slide-down" @show="isReady = true" @before-hide="isReady = false">
      <q-card style="width: 500px; height: 500px">
        <BasicFlow v-show="isReady" />
      </q-card>
    </q-dialog>
  </div>
</template>
```

[Here's a sandbox example.](https://codesandbox.io/s/jovial-cray-t5jpxt?file=/src/components/Dialogs.vue)

I hope this solution works for you 😄

**Closed** 2022-06-03 19:32 UTC
Labels: bug, wontfix

**Comment by hrenly** [comment] 2022-06-06 07:02
@bcakmakoglu
I tried and everything works. Thank you very much again, a very necessary component.
